name: CI
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn example:cli bundle:android
      - run: yarn example:cli bundle:ios
      - run: npm pack --dry-run
